customer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'customer'

urlpatterns = [
    path('sendgig', views.sendgig_view, name='sendgig'), 
    path('profile/', views.profile_page, name="profile"),
    path('payment_method/', views.payment_method, name="payment_method"),
    path('create_gig/', views.create_gig, name="create_gig"),
    
    path('jobs/current/', views.current_jobs, name="current_jobs"),
    path('jobs/archived/', views.archived_jobs, name="archived_jobs"),
    path('jobs/<job_id>/', views.job_page, name="job"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drive_express/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('driver/', include('driver.urls', namespace='driver')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('getstarted', views.getstarted_view, name='getstarted'),
    path('personal-signup', views.personal_signup, name='personal-signup'),
    path('driver-signup', views.driver_signup, name='driver-signup'), 
    path('driver-login', views.drive_login, name='driver-login'), 
    path('sender-login', views.sender_login, name='sender-login'),    
    # path('sendgig', views.sendgig_view, name='sendgig'), 
    # path('drivegig', views.drivegig_view, name='drivegig'),
    path('logout', views.logout, name='logout'),
    path('policy', views.policy, name='policy'),
]

customer/models.py
import uuid
from django.db import models
from django.utils import timezone
from user.models import Personal
from driver.models import Courier



class Category(models.Model):
    slug = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return self.name
    
class Job(models.Model):
    SMALL_SIZE = "small"
    MEDIUM_SIZE = "medium"
    LARGE_SIZE = "large"
    SIZES = (
        (SMALL_SIZE, 'Small'),
        (MEDIUM_SIZE, 'Medium'),
        (LARGE_SIZE, 'Large')
    )

    CREATING_STATUS = 'creating'
    PROCESSING_STATUS = 'processing'
    PICKING_STATUS = 'picking'
    DELIVERING_STATUS = 'delivering'
    COMPLETED_STATUS = 'completed'
    CANCELLED_STATUS = 'cancelled'
    STATUSES = (
        (CREATING_STATUS, 'Creating'),
        (PROCESSING_STATUS, 'Processing'),
        (PICKING_STATUS, 'Picking'),
        (DELIVERING_STATUS, 'Delivering'),
        (COMPLETED_STATUS, 'Completed'),
        (CANCELLED_STATUS, 'Cancelled'),              
    )

    # CUSTOMER_CHOICES = (
    #         ('personal', 'Personal'),
    #         ('entreprise', 'Entreprise'),
    #     )
    
    # step 1
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(Personal, on_delete=models.CASCADE)
    courier = models.ForeignKey(Courier, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    size = models.CharField(max_length=20, choices=SIZES, default=MEDIUM_SIZE)
    quantity = models.IntegerField(default=1)
    photo = models.ImageField(upload_to="job/photos/")
    status = models.CharField(max_length=20, choices=STATUSES, default=CREATING_STATUS)
    created_at = models.DateTimeField(default=timezone.now)
    
    # step 2
    pickup_address = models.CharField(max_length=255, blank=True)
    pickup_lat = models.FloatField(default=0.0)
    pickup_lng = models.FloatField(default=0.0)
    pickup_name = models.CharField(max_length=255, blank=True)
    pickup_phone = models.CharField(max_length=255, blank=True)
    
    # step 3
    delivery_address = models.CharField(max_length=255, blank=True)
    delivery_lat = models.FloatField(default=0.0)
    delivery_lng = models.FloatField(default=0.0)
    delivery_name = models.CharField(max_length=255, blank=True)
    delivery_phone = models.CharField(max_length=255, blank=True)
    
    # step 4
    duration = models.IntegerField(default=0)
    distance = models.FloatField(default=0)
    price = models.FloatField(default=0)
    
    # Extra info
    pickup_photo = models.ImageField(upload_to='job/pickup_photos/', null=True, blank=True)
    pickedup_at = models.DateTimeField(null=True, blank=True)
    
    delivery_photo = models.ImageField(upload_to='job/delivery_photos/', null=True, blank=True)
    delivered_at = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return self.description
    
class Transaction(models.Model):
    stripe_payment_intent_id = models.CharField(max_length=255, unique=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.stripe_payment_intent_id
    

user/customer/forms.py
from django import forms
from django.contrib.auth.models import User

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

customer/views.py
import requests
# import stripe
# import firebase_admin

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from customer import forms
from django.contrib import messages 
from django.conf import settings
from customer.models import *

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


@login_required(login_url="/sender-login/")
def sendgig_view(request):
    return render(request, 'customer/sendgig.html')

@login_required(login_url="/sender-login/")
def profile_page(request):
    user_form = forms.BasicUserForm(instance=request.user)
    customer_form = forms.BasicCustomerForm(instance=request.user)
    password_form = PasswordChangeForm(request.user)
    
    if request.method == 'POST':
        user_form = forms.BasicUserForm(request.POST, instance=request.user)
        customer_form = forms.BasicCustomerForm(request.POST, request.FILES, instance=request.user)
        # password_form = PasswordChangeForm(request.user)

    if request.method == "POST":
        if request.POST.get('action') == 'update_profile':
            user_form = forms.BasicUserForm(
                request.POST, instance=request.user)
            customer_form = forms.BasicCustomerForm(
                request.POST, request.FILES, instance=request.user)

            if user_form.is_valid() and customer_form.is_valid():
                user_form.save()
                customer_form.save()

                messages.success(request, 'Your profile has been updated')
                return redirect(reverse('customer:profile'))

        # elif request.POST.get('action') == 'update_password':
        #     password_form = PasswordChangeForm(request.user, request.POST)
        #     if password_form.is_valid():
        #         user = password_form.save()
        #         update_session_auth_hash(request, user)

        #         messages.success(request, 'Your password has been updated')
        #         return redirect(reverse('customer:profile'))

        # elif request.POST.get('action') == 'update_phone':
        #     # Get Firebase user data
        #     firebase_user = auth.verify_id_token(request.POST.get('id_token'))
        #     request.user.customer.phone_number = firebase_user['phone_number']
        #     request.user.customer.save()
        #     return redirect(reverse('customer:profile'))

    return render(request, 'customer/profile.html', {
        "user_form": user_form,
        "customer_form": customer_form,
        "password_form": password_form
    })
    
    
    # Job posting

@login_required(login_url="/sender-login/")
def create_gig(request):
    current_customer =request.user.personal
    
    has_current_job = Job.objects.filter(
        customer=current_customer,
        status__in=[
            Job.PROCESSING_STATUS,
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).exists()

    if has_current_job:
        messages.warning(request, "You are currently already processing a job")
        return redirect(reverse('customer:current_jobs'))
    
    creating_job = Job.objects.filter(customer=current_customer, status=Job.CREATING_STATUS).last()
    step1_form = forms.JobCreateStep1Form(instance=creating_job)
    step2_form = forms.JobCreateStep2Form(instance=creating_job)
    step3_form = forms.JobCreateStep3Form(instance=creating_job)

    
    if request.method == "POST":
        if request.POST.get('step') == '1':
            step1_form = forms.JobCreateStep1Form(request.POST, request.FILES, instance=creating_job)
            if step1_form.is_valid():
                creating_job = step1_form.save(commit=False)
                creating_job.customer = current_customer
                creating_job.save()
                return redirect(reverse('customer:create_gig'))
            
        elif request.POST.get('step') == '2':
            step2_form = forms.JobCreateStep2Form(request.POST, instance=creating_job)
            if step2_form.is_valid():
                creating_job = step2_form.save()
                return redirect(reverse('customer:create_gig'))
            
        elif request.POST.get('step') == '3':
            step3_form = forms.JobCreateStep3Form(request.POST, instance=creating_job)
            
            if step3_form.is_valid():
                creating_job = step3_form.save()

                try:
                    r = requests.get("https://maps.googleapis.com/maps/api/distancematrix/json?origins={}&destinations={}&mode=transit&key={}".format(
                    creating_job.pickup_address,
                    creating_job.delivery_address,
                    settings.GOOGLE_MAP_API_KEY,
                ))
                    print(r.json()['rows'])
                    
                    distance = r.json()['rows'][0]['elements'][0]['distance']['value']
                    duration = r.json()['rows'][0]['elements'][0]['duration']['value']
                    creating_job.distance = round(distance / 1000, 2)
                    creating_job.duration = int(duration / 60)
                    creating_job.price = creating_job.distance * 1  # $1 per Km
                    creating_job.save()
                                         
                except Exception as e:
                    print(e)
                    messages.error(request, "Unfortunately, we do not support deliveries at this distance.")
               
                return redirect(reverse('customer:create_gig'))
            
        elif request.POST.get('step') == '4':
            if creating_job.price:
        #         try:
        #             payment_intent = stripe.PaymentIntent.create(
        #                 amount=int(creating_job.price * 100),
        #                 currency='usd',
        #                 automatic_payment_methods={"enabled": True},
        #                 customer=current_customer.stripe_customer_id,
        #                 payment_method=current_customer.stripe_payment_method_id,
        #                 off_session=True,
        #                 confirm=True,
        #             )
                    
        #             Transaction.objects.create(
        #                 stripe_payment_intent_id = payment_intent['id'],
        #                 job = creating_job,
        #                 amount = creating_job.price,
        #             )
                    
        #             creating_job.status = Job.PROCESSING_STATUS
        #             creating_job.save()
                    
                    return redirect(reverse('customer:sendgig'))
                    
        #         except stripe.error.CardError as e:
        #             err = e.error
        #             # Error code will be authentication_required if authentication is needed
        #             print("Code is: %s" % err.code)
        #             payment_intent_id = err.payment_intent['id']
        #             payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
                                
    #Determine the current step
    if not creating_job:
        current_step = 1
    elif creating_job.delivery_name:
        current_step = 4
    elif creating_job.pickup_name:
        current_step = 3
    else:
        current_step = 2
                           
    return render(request, 'customer/create_gig.html', {
        "job": creating_job,
        "step": current_step,
        "step1_form": step1_form,
        "step2_form": step2_form,
        "step3_form": step3_form,
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY

    })
       
       
    # Payment method 

@login_required(login_url="/sender-login/")
def payment_method(request):     
    return render(request, 'customer/payment_method.html')

@login_required(login_url="/sender-login/")
def current_jobs(request):
    jobs =Job.objects.filter(
        customer=request.user.personal,
         status__in=[
            Job.PROCESSING_STATUS,
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    )
    
    return render(request, 'customer/gigs.html', {
        "jobs": jobs
    })

@login_required(login_url="/sender-login/")
def archived_jobs(request):
    jobs =Job.objects.filter(
        customer=request.user.personal,
        status__in=[
            Job.COMPLETED_STATUS,
            Job.CANCELLED_STATUS
        ]
    )
    
    return render(request, 'customer/gigs.html', {
        "jobs": jobs
    })
    
    
@login_required(login_url="/sender-login/")
def job_page(request, job_id):
    job =Job.objects.get(id=job_id)
    
    if request.method == "POST" and job.status == Job.PROCESSING_STATUS:
        job.status = Job.CANCELLED_STATUS
        job.save()
        return redirect(reverse('customer:archived_jobs'))
    
    return render(request, 'customer/job.html', {
        "job": job,
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })
    
                

user/customer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from user.customer import forms
from django.contrib import messages
from django.conf import settings
from user.models import *

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


@login_required()
def home(request):
    return redirect(reverse('customer:profile'))

@login_required(login_url="/sender-login/")
def profile_page(request):
    user_form = forms.BasicUserForm(instance=request.user)
    customer_form = forms.BasicCustomerForm(instance=request.user.customer)
    password_form = PasswordChangeForm(request.user)
    
    if request.method == 'POST':
        user_form = forms.BasicUserForm(request.POST, instance=request.user)
        customer_form = forms.BasicCustomerForm(instance=request.user.customer)
        password_form = PasswordChangeForm(request.user)

    if request.method == "POST":

        if request.POST.get('action') == 'update_profile':
            user_form = forms.BasicUserForm(
                request.POST, instance=request.user)
            customer_form = forms.BasicCustomerForm(
                request.POST, request.FILES, instance=request.user.customer)

            if user_form.is_valid() and customer_form.is_valid():
                user_form.save()
                customer_form.save()

                messages.success(request, 'Your profile has been updated')
                return redirect(reverse('customer:profile'))

        elif request.POST.get('action') == 'update_password':
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)

                messages.success(request, 'Your password has been updated')
                return redirect(reverse('customer:profile'))

        # elif request.POST.get('action') == 'update_phone':
        #     # Get Firebase user data
        #     firebase_user = auth.verify_id_token(request.POST.get('id_token'))
        #     request.user.customer.phone_number = firebase_user['phone_number']
        #     request.user.customer.save()
        #     return redirect(reverse('customer:profile'))

    return render(request, 'customer/profile.html', {
        "user_form": user_form,
        "customer_form": customer_form,
        "password_form": password_form
    })
    
    
    # Job posting
@login_required(login_url="/sender-login/")
def create_gig(request):
         
    return render(request, 'customer/create_gig.html')
        
@login_required(login_url="/sender-login/")
def payment_page(request):
         
    return render(request, 'customer/.html')
                

customer/templates/customer/gigs.html
{% extends 'customer/sendgig.html' %}

{% block main %}

{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}

<!-- TABS -->
<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <a class="nav-link {% if request.path == current_jobs_url %}active btn-info{% else %}text-dark{% endif %}"
     href="{% url 'customer:current_jobs' %}">Current Delivery Gig</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == archived_jobs_url %}active btn-info{% else %}text-dark{% endif %}"
     href="{% url 'customer:archived_jobs' %}">Archived Gigs</a>
  </li>
</ul>

<!-- LIST OF JOBS -->
<div class="list-group mt-3">
    {% if jobs %}

    {% for job in jobs %}
    <a href="{% url 'customer:job' job.id %}" class="list-group-item list-group-item-action">
        <div class="media">
            <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
            <div class="media-body">
                <div class="row">

                    <div class="col-lg-9">
                        <h5 class="mb-1">{{ job.name }}</h5>
                        <p>{{ job.description }}</p>

                        <div class="d-flex mb-4">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="ml-2">
                                <b>{{ job.pickup_name }}</b><br/>
                                <small>{{ job.pickup_address }}</small>
                            </div>
                        </div>
                        <div class="d-flex">
                            <i class="fas fa-flag-checkered"></i>
                            <div class="ml-2">
                                <b>{{ job.delivery_name }}</b><br/>
                                <small>{{ job.delivery_address }}</small>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 text-right flex-column justify-content-between">
                        <div><span class="badge badge-info mb-2">{{ job.get_status_display }}</span></div>
                        <h2 class="mb-1">${{ job.price }}</h2>


                    </div>

                </div>
            </div>
        </div>
    </a>


    {% endfor %}

    {% else %}
    <div class="card">
        <div class="card-body text-center">
            Nothing to show here yet.
        </div>
    </div>

    {% endif %}
</div>

{% endblock %}

customer/templates/customer/job.html
{% extends 'customer/sendgig.html' %}
{% load static %} {% block head %}

<style>
  .photo {
    object-fit: cover;
  }

  .photo-blank {
    border: 2px dashed #dfdfdf;
    height: 130px;
    width: 130px;
    border-radius: 5px;
    align-items: center;
    display: flex;
    justify-content: center;
    text-align: center;
    padding: 10px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&callback=initMap&libraries=places&v=weekly"></script>

<script>

    var pickupLat = parseFloat(" {{ job.pickup_lat }} ");
    var pickupLng = parseFloat(" {{ job.pickup_lng }} ");

    var deliveryLat = parseFloat(" {{ job.delivery_lat }} ");
    var deliveryLng = parseFloat(" {{ job.delivery_lng }} ");

  function initMap() {
    const directionsService = new google.maps.DirectionsService();
    const directionsRenderer = new google.maps.DirectionsRenderer();
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 7,
      center: { lat: 41.85, lng: -87.65 },
    });

    directionsRenderer.setMap(map);

    calculateAndDisplayRoute(directionsService, directionsRenderer);
  }

  function calculateAndDisplayRoute(directionsService, directionsRenderer) {
    directionsService
      .route({
        origin: new google.maps.LatLng(pickupLat, pickupLng),
        destination: new google.maps.LatLng(deliveryLat, deliveryLng),
        travelMode: google.maps.TravelMode.DRIVING,
      })
      .then((response) => {
        directionsRenderer.setDirections(response);
      })
      .catch((e) => window.alert("Directions request failed due to " + status));
  }

  window.initMap = initMap;
</script>

{% endblock %} {% block main %}

<!-- JOB DESCRIPTION -->
<div class="media mb-4">
  <img
    src="{{ job.photo.url }}"
    class="rounded-lg mr-3"
    width="150"
    height="150"
  />
  <div class="media-body">

    {% if job.status == 'processing' %}
    <form method="POST" class="float-right">
      {% csrf_token %}
      <button type="submit"class=btn btn-warning>Cancel Job</button>
    </form>
    {% endif %}

    <h4>{{ job.name }}</h4>
    <p class="text-secondary">{{ job.description }}</p>

    <div class="row">
      <div class="col-lg-3">
        <small class="text-secondary">CATEGORY</small><br />
        <span><b>{{ job.category.name }}</b></span>
      </div>
      <div class="col-lg-3">
        <small class="text-secondary">SIZE</small><br />
        <span><b>{{ job.get_size_display }}</b></span>
      </div>
      <div class="col-lg-3">
        <small class="text-secondary">PRICE</small><br />
        <span><b>{{ job.price }}</b></span>
      </div>
      <div class="col-lg-3">
        <small class="text-secondary">QUANTITY</small><br />
        <span><b>{{ job.quantity }}</b></span>
      </div>
    </div>
  </div>
</div>

<!-- DELIVERY INFORMATION -->
<b class="text-secondary">DELIVERY INFORMATION</b><br />
<div class="card bg-white mt-2 mb-5">
  <div class="card-body p-4">
    <h4 class="mb-3">Pickup</h4>
    <div class="row">
      <div class="col-lg-4">
        <b>Address</b><br />
        <span>{{ job.pickup_address }}</span>
      </div>
      <div class="col-lg-4">
        <b>{{ job.pickup_name }}</b><br />
        <span>{{ job.pickup_phone }}</span>
      </div>
      <div id="pickup_photo" class="col-lg-4">
        {% if job.pickup_photo %}
        <img
          src="{{ job.pickup_photo.url }}"
          class="rounded-lg photo"
          width="130"
          height="130"
        />
        {% else %}
        <div class="photo-blank">Pickup Photo Will Appear Here.</div>
        {% endif %}
      </div>
    </div>

    <hr class="my-4" />

    <h4 class="mb-3">Delivery</h4>
    <div class="row">
      <div class="col-lg-4">
        <b>Address</b><br />
        <span>{{ job.delivery_address }}</span>
      </div>
      <div class="col-lg-4">
        <b>{{ job.delivery_name }}</b><br />
        <span>{{ job.delivery_phone }}</span>
      </div>
      <div id="delivery_photo" class="col-lg-4">
        {% if job.delivery_photo %}
        <img
          src="{{ job.delivery_photo.url }}"
          class="rounded-lg photo"
          width="130"
          height="130"
        />
        {% else %}
        <div class="photo-blank">Delivery Photo Will Appear Here.</div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- MAP AREA -->
<div class="d-flex justify-content-between">
  <b class="text-secondary">TRACK DELIVERY</b>
  <div>
    <span class="badge badge-info">{{ job.get_status_display }}</span>
  </div>
</div>

<div class="card bg-white mt-2">
  <div class="card-body p-0">
    <div id="map" style="height: 500px"></div>
  </div>
</div>

{% endblock %}

customer/templates/customer/profile.html
{% extends 'customer/sendgig.html' %}
 {% load bootstrap4 %}
 {% block main %}

<!-- basic Information -->
<b class="text-secondary">Basic Information</b><br />
<div class="card bg-white mt-2 mb-5">
  <div class="card-body">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
       {% bootstrap_form user_form %}
       {% bootstrap_form customer_form %}
      <input type="hidden" name="action" value="update_profile" />
      <button type="submit" class="btn btn-info">Save</button>
    </form>
  </div>
</div>

{% endblock %}

customer/templates/customer/sendgig.html
{% load static %}

{% block content %}

{% url 'customer:create_gig' as create_gig_url %}
{% url 'customer:profile' as profile_url %}
{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}
{% url 'customer:payment_method' as payment_method_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>/Send item</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous" />
</head>

<body>
  <div style="background-color: #dfe9f5">
    <nav
      class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-dark"
      style="background-color: #333"
    >
      <div class="container-fluid">
        <h1 class="text-white"><a href="{{ request.META.HTTP_REFERER }}" style="color: white; text-decoration: none;">DriveXpress</a></h1>
      </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#"
            >{{user.username}}!</a
          >
        </li>
        <a href="{% url 'user:logout' %}"
          ><button
            class="btn btn-info btn-lg"
            type="submit"
            style="width: 100px; height: 45px"
          >
            Logout
          </button></a
        >
      </ul>
    </nav>
    
    <h2 class="text-center">Make your delivery request anytime, anywhere!</h2>
    <div>
      {% for message in message_profile %}
      <h5 style="color: goldenrod">{{message}}</h5>
      {% endfor %}
    </div>
    <div class="container bg-light mt-4 pt-3 pb-3 text-left rounded-lg">
      <div class="row">
        <div class="col-lg-4">
          <div class="text-center">
            <img
              src="{% if request.user.customer.avatar %}{{ request.user.customer.avatar.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}"
              alt="" class="rounded-circle mb-2" width="100" height="100" />
            <h4>{{ request.user.get_full_name }}</h4>
            <p class="text-secondary">{{ request.user.email }}</p>
          </div>

          <ul class="list-group mt-5">
            <a href="{% url 'customer:create_gig' %}"
              class="list-group-item list-group-item-action {% if request.path == create_gig_url %}active btn-info{% else %}text-dark{% endif %}">Post
              Delivery Gig</a>
            <a href="{% url 'customer:current_jobs' %}"
              class="list-group-item list-group-item-action {% if request.path == current_jobs_url or request.path == archived_jobs_url %}active btn-info{% else %}text-dark{% endif %}">My
              Gigs</a>
            <a href="{% url 'customer:profile' %}"
              class="list-group-item list-group-item-action {% if request.path == profile_url %}active btn-info{% else %}text-dark{% endif %}">Profile
              Details</a>
            <a href="{% url 'customer:payment_method' %}"
              class="list-group-item list-group-item-action {% if request.path == payment_method_url %}active btn-info{% else %}text-dark{% endif %}">Payment
              Details</a>
          </ul>

        </div>
        <div class="col-lg-8">{% block main %} {% endblock %}</div>
      </div>
    </div>
    <br />
    <footer class="text-center mt-5 mb-5">&copy; DriveX.com</footer>
    <br />
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
</body>

</html>
{% endblock %}