drive_express/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('driver/', include('driver.urls', namespace='driver')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('getstarted', views.getstarted_view, name='getstarted'),
    path('personal-signup', views.personal_signup, name='personal-signup'),
    path('driver-signup', views.driver_signup, name='driver-signup'), 
    path('driver-login', views.drive_login, name='driver-login'), 
    path('sender-login', views.sender_login, name='sender-login'),    
    # path('sendgig', views.sendgig_view, name='sendgig'), 
    # path('drivegig', views.drivegig_view, name='drivegig'),
    path('logout', views.logout, name='logout'),
    path('policy', views.policy, name='policy'),
]

user/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class Personal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='customer/avatars/', blank=True, null=True)
    firstname = models.CharField(max_length=20, blank=True)
    lastname = models.CharField(max_length=20, blank=False)
    mobile = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=50, blank=False, unique=True, primary_key=True)
    password = models.CharField(max_length=255, blank=False)
    
    def __str__(self):
        return self.user.username
    
    
class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=20, blank=False, null=False)
    lastname = models.CharField(max_length=20, blank=False, null=False)
    mobile = models.CharField(max_length=20, null=False, blank=False)
    email = models.EmailField(max_length=50, blank=False, unique=True)
    password = models.CharField(max_length=255, blank=False)
                
    def __str__(self):
        return self.user.username
    
#class Personal(AbstractUser):
    
    # pass

user/customer/forms.py
from django import forms
from django.contrib.auth.models import User

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

user/forms.py
from django import forms

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='Email')

user/customer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from user.customer import forms
from django.contrib import messages
from django.conf import settings
from user.models import *

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


@login_required()
def home(request):
    return redirect(reverse('customer:profile'))

@login_required(login_url="/sender-login/")
def profile_page(request):
    user_form = forms.BasicUserForm(instance=request.user)
    customer_form = forms.BasicCustomerForm(instance=request.user.customer)
    password_form = PasswordChangeForm(request.user)
    
    if request.method == 'POST':
        user_form = forms.BasicUserForm(request.POST, instance=request.user)
        customer_form = forms.BasicCustomerForm(instance=request.user.customer)
        password_form = PasswordChangeForm(request.user)

    if request.method == "POST":

        if request.POST.get('action') == 'update_profile':
            user_form = forms.BasicUserForm(
                request.POST, instance=request.user)
            customer_form = forms.BasicCustomerForm(
                request.POST, request.FILES, instance=request.user.customer)

            if user_form.is_valid() and customer_form.is_valid():
                user_form.save()
                customer_form.save()

                messages.success(request, 'Your profile has been updated')
                return redirect(reverse('customer:profile'))

        elif request.POST.get('action') == 'update_password':
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)

                messages.success(request, 'Your password has been updated')
                return redirect(reverse('customer:profile'))

        # elif request.POST.get('action') == 'update_phone':
        #     # Get Firebase user data
        #     firebase_user = auth.verify_id_token(request.POST.get('id_token'))
        #     request.user.customer.phone_number = firebase_user['phone_number']
        #     request.user.customer.save()
        #     return redirect(reverse('customer:profile'))

    return render(request, 'customer/profile.html', {
        "user_form": user_form,
        "customer_form": customer_form,
        "password_form": password_form
    })
    
    
    # Job posting
@login_required(login_url="/sender-login/")
def create_gig(request):
         
    return render(request, 'customer/create_gig.html')
        
@login_required(login_url="/sender-login/")
def payment_page(request):
         
    return render(request, 'customer/.html')
                

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout as auth_logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from .models import Personal, Driver


def home_view(request):
    return render(request, 'home.html')

def getstarted_view(request):
    return render(request, 'user/getstarted.html')

# Personal views
# Handle personal signup form submission
def personal_signup(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        mobile = request.POST['mobile']
        
        if User.objects.filter(email=email).exists():
            messages.info(request, 'email already exists!')
            return redirect('/personal-signup')
        elif User.objects.filter(username=firstname).exists():
            messages.info(request, 'username taken!')
            return redirect('personal-signup')
        
        else:
            user = User.objects.create_user(
            username=firstname,
            email=email,
            password=password
        )
            user.last_name = lastname
            user.mobile = mobile
            user.save()
            
        personal = Personal.objects.create(
                user=user,
                username=firstname,
                lastname=lastname,
                mobile=mobile,
                email=email,
                password=password
            )
        # user.set_password(password)
        # personal.save()
        subject = 'welcome to DriveX!'
        message = f'Hello {user.username}, thank you for signing up fo DriveX delivery service.'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [user.email, ]
        send_mail( subject, message, email_from, recipient_list )
        return redirect('/sender-login')
            
    else:     
        return render(request, 'user/personal-signup.html')
    
# Handle personal login form submission
# Perform authentication and login logic for personal user
def sender_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('customer:sendgig')
        else:
            messages.error(request, 'Invalid credentials!')
            return redirect('user:sender-login')
    
    return render(request, 'user/sender-login.html')

# Logout user
def logout(request):
    auth_logout(request)
    return redirect('/')
     

# Driver views
# Handle driver signup form submission
def driver_signup(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        mobile = request.POST['mobile']
        email = request.POST['email']
        password = request.POST['password']
        
        if User.objects.filter(email=email).exists():
            messages.info(request, 'email already exists!')
            return redirect('/driver-signup')
        elif User.objects.filter(username=firstname).exists():
            messages.info(request, 'driver license already exists!')
            return redirect('/driver-signup')
        
        else:
            user = User.objects.create_user(
            username=firstname,
            email=email,
            password=password
        )
            user.last_name = lastname
            user.mobile = mobile
            user.save()
            
        driver = Driver.objects.create(
                user=user,
                firstname=firstname,
                lastname=lastname,
                mobile=mobile,
                email=email,
                password=password
            )
        # user.set_password(password)
        # driver.save()
        subject = 'welcome to DriveX!'
        message = f'Hello {user.username}, thank you for signing up fo DriveX delivery service.'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [user.email, ]
        send_mail( subject, message, email_from, recipient_list )
        return redirect('/driver-login')
            
    else:
        return render(request, 'user/driver-signup.html')

# Handle driver login form submission
# Perform authentication and login logic for driver user
def drive_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('driver:drivegig')
        else:
            messages.error(request, 'Invalid credentials!')
            return redirect('user:driver-login')
    
    return render(request, 'user/driver-login.html')

# def sendgig_view(request):
#     return render(request, 'customer/sendgig.html')

def drivegig_view(request):
    return render(request, 'user/drivegig.html')

def policy(request):
    return render(request, 'user/policy.html')

def profile_page(request):
    return render(request, 'customer/profile.html')

login_required(login_url="/sender-login?next=/customer/")
def create_gig(request):
         
    return render(request, 'customer/create_gig.html')
        
        

user/templates/user/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Contact</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <div class="text-center">
        <h2>Get in touch</h2>
        <p class="lead">Questions? Do not hesitate to contact us!</p>

        <div class="form-floating my-5">
          <textarea
            name="query"
            id="query"
            style="height: 200px"
            class="form-control"
            placeholder="write a message..."
          >
          </textarea>
          <label for="query">Write a message</label>
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user/templates/user/dataprivacy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy policy</title>
</head>
<body>
    <p>
        <h1>Privacy Policy: DriveXpress</h1>
        <h2>Effective Date: May 1, 2023</h2>
        At DriveX, we value your privacy and are committed to protecting your personal information. This Privacy<br>
        Policy outlines how we collect, use, disclose, and protect your data when you use our on-demand delivery system.<br>
        By accessing and using our services, you consent to the practices described in this policy. Please read this policy carefully.
    </p>
    <p>
        Information We Collect:<br>
        1.1 Personal Information: When you create an account and use our on-demand delivery system, we may collect personal information<br>
        such as your name, email address, phone number, delivery addresses, and payment details. We only collect the information<br>
        necessary to provide our services effectively.
        1.2 Usage Data: We may collect data related to your interactions with our platform, including log files, IP addresses, device<br>
         information, browser type, and usage patterns. This information helps us improve our services and provide a better user experience.
    </p>
    <p>
        Use of Information:<br>
        2.1 Service Provision: We use the information collected to facilitate the delivery of requested items, manage your account, <br>
        and provide<br> customer support. This includes order processing, delivery coordination, and resolving any issues that may arise.<br>
        2.2 Communication: We may use your contact information to send transactional notifications, updates about your orders, service-related<br>
        announcements, and important account information. 
        2.3 Personalization: With your consent, we may use your information to personalize your experience, provide tailored recommendations,<br>
        and offer promotions or discounts that may be of interest to you.
        2.4 Analytics and Improvements: We may analyze aggregated data to better understand user preferences, improve our services, and <br>
        enhance the overall functionality of our platform.
    </p>
    <p>
        Data Sharing:<br>
        3.1 Third-Party Service Providers: We may share your personal information with trusted third-party service providers who assist <br>
        us in delivering our services. These providers include delivery personnel, payment processors, customer support platforms, and <br>
        data analytics tools. However, we ensure that they adhere to strict confidentiality and data protection standards.
        3.2 Legal Compliance: We may disclose your personal information if required by law, regulation, legal process, or government request.<br>
        3.3 Business Transfers: In the event of a merger, acquisition, or sale of assets, your personal information may be transferred to the acquiring entity, subject to their adherence to this Privacy Policy.
    </p>
    <p>
        Data Security:<br>
        4.1 Security Measures: We implement industry-standard security measures to protect your personal information from unauthorized<br>
        access, disclosure, alteration, or destruction. These measures include encryption, secure socket layer (SSL) technology, access<br>
        controls, and regular security audits.
        4.2 User Responsibilities: While we take reasonable precautions, it is important for you to also protect your account and personal<br>
        information by using strong passwords, keeping your login credentials confidential, and promptly reporting any unauthorized activities or security concerns.
    </p>
    <p>
        Data Retention:<br>
        We retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer<br>
        retention period is required or permitted by law. Once the data is no longer needed, we will securely dispose of it in accordance <br>
        with our data retention policies.
    </p>
    <p>
        Your Rights:<br>
        6.1 Access and Control: You have the right to access, correct, update, or delete your personal information. You can manage your account <br>
        settings and preferences through the platform or by contacting our customer support team.
        6.2 Marketing Communications: You can choose to opt-out of receiving promotional emails or marketing communications from us by following <br>
        the unsubscribe instructions provided in the emails.
        6.3 Do Not Track: Our platform does not respond to "Do Not Track" signals. However, you can adjust your browser settings to disable tracking<br>
        technologies.
    </p>
    <p>
        Changes to the Privacy Policy:<br>
        We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material<br>
        changes by posting the updated policy on our website or sending a direct communication. It is your responsibility to review this policy periodically.
    </p>
    <p>
        If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us through the<br>
        designated channels provided on our platform.
    </p>
</body>
</html>

user/templates/user/drive-login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sender Sign-in</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="getstarted.css" type="text/css" />
  </head>
  <body>
    <form>
      <div class="container">
        <div class="h1">
          <h1>Driver Sign in</h1>
        </div>
        <div class="login">
          <label for="exampleInputEmail1" class="form-label"
            >Email address</label
          >
          <input
            type="email"
            class="form-control"
            id="exampleInputEmail1"
            aria-describedby="emailHelp"
          />
        </div>

        <div class="login">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input
            type="password"
            class="form-control"
            id="exampleInputPassword1"
          />
        </div>

        <button type="submit" class="btn btn-primary">login</button>
      </div>
    </form>

    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user/templates/user/driver-login.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sender Sign-in</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static '/user/user.css'%}"
      type="text/css"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-dark"
      style="background-color: #333"
    >
      <a class="navbar-brand" href="/"><h1>DriveXpress</h1></a>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#"
            >Driver Login!</a
          >
        </li>
      </ul>
    </nav>
    <div>
      {% for message in messages %}
      <h5 style="color: coral">{{message}}</h5>
      {% endfor %}
    </div>
    <div class="wrapper2">
      <h2>Driver Sign In</h2>
      <form action="{% url 'user:driver-login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="email" placeholder="Email Address" />
        <input type="password" name="password" placeholder="Password" />
        <button type="submit">Sign In</button>
      </form>
      <div class="member">
        New to DriveX? <a href="{% url 'user:driver-signup' %}">Register Now</a>
      </div>
    </div>
    <footer class="text-center mt-5 mb-5">&copy; DriveX.com</footer>
  </body>
</html>
{% endblock %}

user/templates/user/driver-signup.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Driver Sign Up</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
    <link
      href="{% static '/user/user.css'%}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-dark"
      style="background-color: #333"
    >
      <a class="navbar-brand" href="/"><h1>DriveXpress</h1></a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Driver SignUp!</a>
        </li>
      </ul>
    </nav>
    <div>
      {% for message in messages %}
      <h5 style="color: coral">{{message}}</h5>
      {% endfor %}
    </div>
    <div class="wrapper">
      <h3>Driverer Sign Up</h3>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="firstname" placeholder="First Name" />
        <input type="text" name="lastname" placeholder="Last Name" />
        <input type="tel" name="mobile" placeholder="Phone Number" />
        <input type="email" name="email" placeholder="Email Address" />
        <input type="password" name="password" placeholder="Password" />
        <button type="submit">Continue</button>
      </form>
      <div class="terms">
        <label for="checkbox"
          >By signing up, I agree to<br />
          DriveX's <a href="#">Privacy and Terms.</a></label
        >
      </div>

      <div class="member">
        Have an account? <a href="{% url 'user:driver-login' %}">Login Here</a>
      </div>
    </div>
    <footer class="text-center mt-5 mb-5">&copy; DriveX.com</footer>
  </body>
</html>
{% endblock %}

user/templates/user/drivers page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

user/templates/user/drivers sign-up.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Drivers Sign-up</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>

    
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user/templates/user/drivers-signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Driver Sign Up</title>
    <link href="register.css" rel="stylesheet" type="text/css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
  </head>
  <body>
    <div class="header">
    <h1>
      Get Paid to Drive,<br>your way.</h1><br />
      <h3>Earn cash on trips you're already taking, whether you drive<br>
         across town or across state lines, DriveX is an easy, flexible<br>
          way to make money driving.</h3>
    </div>
    <div class="wrapper">
      <h2>Driver Sign Up</h2><br>
      <h3>By signing up, I agree to DriveX's <a href="#">Privacy and Terms.</a></h3>
      <form action="#">
        <input type="text" placeholder="First Name" />
        <input type="text" placeholder="Last Name" />
        <input type="text" placeholder="Licence Number" />
        <input type="text" placeholder="Email Address" />
        <input type="tel" placeholder="Phone Number" />
        <input type="password" placeholder="Password" />
        <input type="password" placeholder="Re-Enter Password" />
      </form>

      <button>Continue</button>
      
    </div>
  </body>
</html>

user/templates/user/sender-login.html
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sender Sign-in</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <link rel="stylesheet" href="{% static '/user/user.css'%}" type="text/css" />
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-dark" style="background-color: #333">

    <a class="navbar-brand" href="/">
      <h1>DriveXpress</h1>
    </a>

    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active text-white" aria-current="page" href="#">Sender Login!</a>
      </li>  
    </ul>
  </nav>
  <div>
    {% for message in messages %}
    <h5 style="color: coral">{{message}}</h5>
    {% endfor %}
  </div>
  <div class="wrapper2">
    <h2>Sender Sign In</h2>
    <form action="{% url 'user:sender-login' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="email" placeholder="Email Address" />
      <input type="password" name="password" placeholder="Password" />
      <button type="submit">Sign In</button>
    </form>
    <div class="member">
      Not a member?
      <a href="{% url 'user:personal-signup' %}">Register Now</a>
    </div>
  </div>
  <footer class="text-center mt-5 mb-5">&copy; DriveX.com</footer>
</body>

</html>
{% endblock %}