drive_express/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('driver/', include('driver.urls', namespace='driver')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

driver/urls.py
from django.urls import path
from driver import views
from django.conf import settings
from django.conf.urls.static import static
from driver import apis as courier_apis

app_name = 'driver'

urlpatterns = [
    path('drivegig', views.drivegig_view, name='drivegig'),
    path('api/available/gigs', courier_apis.available_jobs_api, name='available_jobs_api')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('getstarted', views.getstarted_view, name='getstarted'),
    path('personal-signup', views.personal_signup, name='personal-signup'),
    path('driver-signup', views.driver_signup, name='driver-signup'), 
    path('driver-login', views.drive_login, name='driver-login'), 
    path('sender-login', views.sender_login, name='sender-login'),    
    # path('sendgig', views.sendgig_view, name='sendgig'), 
    # path('drivegig', views.drivegig_view, name='drivegig'),
    path('logout', views.logout, name='logout'),
    path('policy', views.policy, name='policy'),
]

driver/models.py
from django.db import models
import uuid
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone

class Courier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.get_full_name()

driver/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.conf import settings
from user.models import *

@login_required(login_url="/driver-login/")
def drivegig_view(request):
    return render(request, 'driver/drivegig.html', {
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY,
    })

driver/templates/driver/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Courier | DriveX</title>

    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <script>
      let vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty('--vh', `${vh}px`);
    </script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" />
    <link rel="stylesheet" href="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.css" />

    <style>
      #content {
            height: calc(var(--vh, 1vh) * 100);
        }
    </style>

    {% block head %}{% endblock %}
</head>

<body>
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-dark" style="background-color: #333">
      <div class="container-fluid">
        <h1 class="text-white">DriveXpress</h1>
      </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#" 
          style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 200px;">Hello {{ request.user.get_full_name | title }}!</a>
        </li>
        <a href="{% url 'user:logout' %}"><button class="btn btn-info btn-lg" type="submit"
            style="width: 100px; height: 45px">
            Logout
          </button></a>
      </ul>
    </nav>
    <!-- body content -->
    <div id="content">
      {% block content %}{% endblock %}
    </div>

    <!-- footer -->
    <!-- <footer class="text-center mt-5 mb-5">&copy; DriveX.com</footer>
    {% block footercontent %}{% endblock footercontent %} -->

    <!-- scripts -->
    <!-- {% block scripts %}{% endblock scripts %} -->
    <!-- <script src="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.js"></script>
    <script>
        function toast(message, type) {
            bootoast.toast({
                position: 'leftBottom',
                message,
                type
            })
        }
    </script>
    {% if messages %}
    {% for message in messages %}
    <script>
        toast('{{ message }}', '{{ message.tags }}')
    </script>
    {% endfor %}
    {% endif %} -->
</body>

</html>

driver/templates/driver/bottom_tabs.html
<style>
    .bottom-tabs {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        height: 60px;
        display: flex;
        background-color: white;
        box-shadow: 0 1px 5px rgba(0, 0, 0, 0.2);
        text-align: center;
    }

    .bottom-tabs>a {
        flex: 1;
        padding: 5px;
        color: #BFBFBF;
        text-decoration: none;
    }

    .bottom-tabs>a>span {
        font-size: 13px;
        font-weight: bold;
        display: block;
    }

    .bottom-tabs>a>i {
        font-size: 20px;
    }

    .bottom-tabs>a.active {
        color: #058283;
    }
</style>


<div class="bottom-tabs d-flex">
    <a href="#" class="active">
        <i class="fas fa-map-marked-alt"></i>
        <span>Available Gigs</span>
    </a>
    <a href="#">
        <i class="fas fa-archive"></i>
        <span>My Deliveries</span>
    </a>
    <a href="#">
        <i class="fas fa-user"></i>
        <span>Profile</span>
    </a>
</div>

driver/templates/driver/drivegig.html
{% extends 'driver/base.html' %} {% block head %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAPf-PH9qBF_HugsrYjn_lXTJlFvhE0Wk&callback=initMap&libraries=places&v=weekly"></script>
<script>
  function initMap() {
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 13,
      center: { lat: -1.2921, lng: 36.8219 },
    });

    // Get available jobs via API
    fetch("{% url 'driver:available_jobs_api' %}")
      .then((res) => res.json())
      .then((json) => {
       //  console.log(json);
       
       for (let i=0; i < json.jobs.length; i++) {
        const job = json.jobs[i]
        const position = { lat: job.pickup_lat, lng: job.pickup_lng };
        const marker = new google.maps.Marker({
                        position: position,
                        map
                        });

                    bounds.extend(position)

                    new google.maps.InfoWindow({
                        content: "<small><b>" + job.name + "</b></small><br /><small>" + job.distance + " Km</small>"
                    }).open(map, marker)

                    // click event job
                    marker.addListener("click", () => {
                        showJobDetails(job)
                    })

                    map.fitBounds(bounds)
       }

      })
  }

  // Call initMap when the page finishes loading
  window.addEventListener("load", function () {
    initMap();
  });
</script>

<style>
  .gm-ui-hover-effect {
    display: !important;
  }
  #map {
    flex: 1;
  }
</style>

{% endblock %} {% block content %}

<div class="d-flex flex-column h-100" style="padding-bottom: 60px">
  <div id="map"></div>
</div>

{% include 'driver/bottom_tabs.html' %} {% endblock %}